### PR TITLE
Fix for issue 6

### PR DESCRIPTION
**Pull request by quickshiftin**
This is a fix for [the issue](https://github.com/Iazel/magento2-regenurl/issues/11) I just opened in you repo.

### CODE REVIEW

**Comment by sergy-gzh** [comment]
Nice, when this fix is going to be merged?

**Comment by ghost** [comment]
Created a new version of the extension with all the fixes and improvements. A this module doesn't seems to be maintained anymore.

**Comment by ghost** [comment]
https://github.com/experius/Magento2-Module-Experius-ReindexCatalogUrlRewrites

**Comment by iazel** [comment]
Merged a similar PR

**Pull request closed without merging**
