### PR TITLE
Fixes Iazel/magento2-regenurl#11 & Iazel/magento2-regenurl#13

### PR DESCRIPTION
**Pull request by grafikchaos**
Avoids the LocalizedException error message 'Area code is already set'
by first checking to see if the area code is set or not. If area code is
not set, then set it to 'adminhtml'

### CODE REVIEW

**Comment by gediminaskv** [comment]
Now it shows:

[Magento\Framework\Exception\LocalizedException]
  Area code is not set

**Comment by gewaechshaus** [comment]
It should be moved through the execute method!

**Comment by iazel** [comment]
Thanks for your contribution :)

**Comment by andrewhowdencom** [comment]
As @gediminaskv, this does not resolve the fix. Invoking the command shows the same error

**Comment by grafikchaos** [comment]
EDIT: issue #20 seems to have the most up-to-date fix for this recurring issue.

@gediminaskv and @andrewhowdencom - the code has already been merged in. Create a new issue or open up the original issues

**Comment by andrewhowdencom** [comment]
Will dooo

**Pull request merged**
